[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="currUser" type="com.tonglukuaijian.survey.sercurity.UserExt" --]
[#-- @ftlvariable name="global.pageable" type="freemarker.core.Macro" --]
[#-- @ftlvariable name="pageAllTitle" type="String" --]
[#-- @ftlvariable name="pageTitle" type="String" --]
[#-- @ftlvariable name="pageMetaContent" type="String" --]
[#-- @ftlvariable name="pageCss" type="String" --]
[#-- @ftlvariable name="pageScripts" type="String" --]
[#-- @ftlvariable name="bodyProperties" type="String" --]
[#-- @ftlvariable name="appConfig" type="com.tonglukuaijian.survey.context.AppConfigExt" --]
[#-- @ftlroot "../webapp/WEB-INF/content" --]